apiVersion: v1
kind: Service
metadata:
  name: pythonwebapp-service
spec:
  selector:
    app: pythonwebapp
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonwebapp
spec:
  selector:
    matchLabels:
      app: pythonwebapp
  replicas: 3
  template:
    metadata:
      labels:
        app: pythonwebapp
    spec:
      containers:
      - name: pythonwebapp
        image: docker.io/localhost/pythonwebapp:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: 200Mi
            cpu: 500m
          requests:
            memory: 50Mi
            cpu: 125m
